### ISSUE TITLE
Error in loading "topicmodels" package for R docker

### ISSUE THREAD

**Issue by ShimantoRahman** [dodona-edu/docker-images#228]
In commit [#244a381](https://github.com/dodona-edu/docker-images/commit/244a381d4e97a32fef3743652afb24f2870eee70) many R packages were added to the R docker, one of which being "topicmodels".
However, there occurred an error while installing this package:
```ctm.c:29:10: fatal error: gsl/gsl_rng.h: No such file or directory```
line 16855 in the R Publish to Registry section ([here](https://github.com/dodona-edu/docker-images/runs/3936134970))

While looking up this error message I came across someone experiencing a silimar issue on [this blogpost](https://tinyheero.github.io/2016/02/20/install-r-topicmodels.html) and [this stackoverflow post](https://stackoverflow.com/questions/24172188/how-can-i-install-topicmodels-package-in-r).
There seems to be an issue surrounding the installation of GSL ([The GNU Scientific Library](http://www.gnu.org/software/gsl/)).
I am out of my depth when it comes to implementing this fix on docker.
Could someone please aid me in solving this issue to we can use the topicmodels package in our Dodona exercises using the R-judge?

**Comment by chvp** [comment]
I'll take a look tomorrow. I usually monitor for package build errors when adding R packages, but clearly forgot to do so here.

**Comment by chvp** [comment]
This was fixed by #230.
